# Created using wingetcreate

PackageIdentifier: LibreSprite.LibreSprite
PackageVersion: 1.0
Installers:
- Architecture: neutral
  InstallerType: exe
  InstallerUrl: https://github.com/LibreSprite/LibreSprite/releases/download/_tmp/LibreSpriteWin.exe
  InstallerSha256: 0B97559DDB9979F67836941B52CAADAFBA37C22B639AA8BC0643CD17916A5324
ManifestType: installer
ManifestVersion: 1.0.0
